### ISSUE TITLE
数据库初始化脚本没有提供

### ISSUE THREAD

**Issue by singer-cheng** [wangcl/admin-boot#1]
项目中没有找到数据库建表和初始化SQL文件

**Comment by wangcl** [comment]
见 `ddl.sql` 和 `dml.sql` 。因原始文件无保留，所以根据 `mapper` 生成了ddl，补充了一些初始数据。
这是很久以前的demo项目了（保持最简），实际项目需要根据业务需求补充。
这种传统（老式）的技术栈有其特定的使用场景，如果是新项目，还是建议采用现代的框架。
